  
version: 2
jobs:
  build:
    machine: true # Build using our custom docker build image
    working_directory: ~/dietstory-routing
    
    steps:
      - checkout # check out the code in the project directory
      - run: # Run Dietstory Django Server Tests
          name: Run Dietstory Django Server Tests
          command: |
            docker run --rm --env BUILD_SOURCE=local -v $(pwd):/mnt benjixd/dietstory-django-tests
      - store_artifacts:
          path: dietstory-routing
          
