  
version: 2
jobs:
  build:
    machine: true # Build using our custom docker build image
    working_directory: ~/dietstory-routing
    
    steps:
      - checkout # check out the code in the project directory            
      - store_artifacts:
          path: dietstory-routing
          
