# Generated by Django 2.2.6 on 2019-11-24 20:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_id_major', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('version_id_minor', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('file_name', models.CharField(max_length=128)),
                ('s3_path', models.CharField(max_length=128)),
                ('hash_value', models.CharField(max_length=128)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'game_files',
                'managed': True,
                'unique_together': {('version_id_major', 'version_id_minor', 'file_name')},
            },
        ),
    ]
