export const START_GAME_CLIENT_SUCCESS = 'START_GAME_CLIENT_SUCCESS';
export const START_GAME_CLIENT_FAIL = 'START_GAME_CLIENT_FAIL';
export const CHECK_GAME_CLIENT_STATUS = 'CHECK_GAME_CLIENT_STATUS';