export const FETCHING_LOGIN_REWARDS = 'FETCHING_LOGIN_REWARDS';
export const UPDATE_LOGIN_REWARDS = 'UPDATE_LOGIN_REWARDS';
export const LOGIN_REWARDS_ERROR = 'LOGIN_REWARDS_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const COLLECT_REWARD = 'COLLECT_REWARD';