export const CHECKING_FOR_UPDATE = 'CHECKING_FOR_UPDATE';
export const UPDATE_CHECK_FAILED = 'UPDATE_CHECK_FAILED';
export const IS_LATEST_VERSION = 'IS_LATEST_VERSION';
export const UPDATE_AVAILABLE = 'UPDATE_AVAILABLE';
