export const FILE_UPLOAD_START = 'FILE_UPLOAD_START';
export const SET_FUTURE_VERSIONS = 'SET_FUTURE_VERSIONS';
export const SET_STATUS = 'SET_STATUS';
export const SET_RESULT = 'SET_RESULT';
export const RESET_STATE = 'RESET_STATE';